apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: norvoter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: norvoter-backend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: norvoter
        - name: DB_USER
          value: postgres2
        - name: DB_PASSWORD
          value: 1qaz
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin123
        - name: MINIO_BUCKET
          value: meters
        - name: MINIO_ENDPOINT
          value: minio:9000
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: norvoter
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000